### ISSUE TITLE
Please add support for timeout and retries.

### ISSUE THREAD

**Issue by maryshaheen** [newrelic/nri-snmp#24]
## Is your feature request related to a problem? Please describe.
I am seeing that snmp often needs a retry to collect information.  This is causing data holes
## Feature Description
In the code, the snmp timeout is set to 10s.  That is good.  It would be great to have that as a customizable argument.  Perhaps with a min/max.
I didn't come across code for retries.  It would be great to have that as a customizable argument.  Perhaps with a min/max.

## Additional context
Add any other context here.
![image](https://user-images.githubusercontent.com/73126481/96475145-aa845a80-1201-11eb-997b-ea2b053a7014.png)

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Nice to Have, Really Want, Must Have, Blocker] 
Blocker.   We're not able to implement with so much lost info.  Having reliable alerts is also important and cannot be reliable with so much data missing.

**Comment by carlossscastro** [comment]
Hi @maryshaheen 

We have released [v1.3.0](https://github.com/newrelic/nri-snmp/releases/tag/v1.3.0) which implements timeout, retries and exponential backoff.
This should help with your use case.

You can find more information on the new settings on our documentation:
https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/snmp-monitoring-integration/#host-connection

Hope this helps.

Thanks for creating this issue and contribute to improve our integration.
