### ISSUE TITLE
apt-get install unclear and not working

### ISSUE THREAD

**Issue by icpenguins** [newrelic/nri-snmp#26]
## Description
I followed the documentation to install the `nri-snmp` integration through the various documentation hoops ([Install On-host](https://docs.newrelic.com/docs/integrations/host-integrations/installation/install-infrastructure-host-integrations)). The link from the [SNMP](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/snmp-monitoring-integration) guide points to that link. At that location, it calls the integration the `nri-snmp` file. However, when doing this on Ubuntu 20.x, it isn't found.

```bash
...@...:~$ sudo apt-get install nri-snmp
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package nri-snmp
```

## Expected Behavior
The documentation all states that this should work. If it shouldn't work, then it should be called out correctly.

**Comment by josemore** [comment]
Ubuntu 20 (focal) was added around November so this should be supported now.
