### ISSUE TITLE
Configuration file in public docs is inconsistent with config full pulled down for repository

### ISSUE THREAD

**Issue by bl25322** [newrelic/nri-snmp#5]
This is the sample pulled down...

# Configuration file template, provided in case you want to provide extra
# configuration over the nr-nri-snmp-config.yml
# file.
#
# For a complete description of the Configuration File Specification, please
# refer to the Integrations SDK documentation:
# https://docs.newrelic.com/docs/integrations/integrations-sdk/file-specifications

integration_name: com.newrelic.snmp

instances:
  - name: <INSTANCE IDENTIFIER>
    command: metrics
    arguments:
      hostname: localhost
      port: 161
      community: public
      collection_files: "/etc/newrelic-infra/integrations.d/snmp-metrics.yml"
    labels:
      key1: <LABEL_VALUE>

  - name: <OTHER INSTANCE IDENTIFIER>
    command: inventory
    arguments:
      hostname: localhost
      port: 161
      community: public
      collection_files: "/etc/newrelic-infra/integrations.d/snmp-metrics.yml"
    labels:
      key1: <LABEL_VALUE>

This is the public documentation....

integration_name: com.newrelic.snmp

	instances:
	  - name: snmp
	    command: all_data
	    arguments:
	      snmp_host: localhost
	      snmp_port: 161
          v2: true
	      community: public
	      collection_files: "/etc/newrelic-infra/integrations.d/snmp-metrics.yml"
	
The latter with snmp_host appears correct...

**Comment by preddy-newrelic** [comment]
Thank you for filing this issue. I have since fixed it.
