### ISSUE TITLE
PrivProtocol not correctly supported

### ISSUE THREAD

**Issue by Steve24by7** [newrelic/nri-snmp#7]
Notice from util.go lines 24ff
This should say 
args.PrivProtocol ==  "AES"
and
args.PrivProtocol ==  "DES"

		privProtocol := gosnmp.AES
		if args.AuthProtocol == "AES" {
			privProtocol = gosnmp.AES
		} else if args.AuthProtocol == "DES" {
			privProtocol = gosnmp.DES
		} else {
			log.Error("Invalid priv_protocol %s. Defaulting to AES", privProtocol)
		}

**Comment by preddy-newrelic** [comment]
Thanks steve, finally fixed all SNMP v3 issues in release 1.1.3
